### ISSUE TITLE
Character escaping missing in mailbox::to_xml(const char*)

### ISSUE THREAD

**Issue by SebastianBecker2** [otris/ews-cpp#104]
When a mailbox is serialized with mailbox::to_xml(const char*), the text in name and value is not escaped.

    ews::calendar_item item;
    item.set_start(ews::date_time("2018-01-20T17:00:00.000Z"));
    item.set_end(ews::date_time("2018-01-20T18:00:00.000Z"));
    item.set_body(ews::body("test"));
    item.set_required_attendees({ ews::attendee(ews::mailbox("bla", "blä")) });
    service.create_item(item);

The above causes an internal server error. (
I will dig a little deeper tomorrow.

**Comment by SebastianBecker2** [comment]
Just the usual encoding problem.
All strings have to be encoded as UTF-8. Which is not the case in the above mentioned example. "blä" is encoded using the charset/encoding used by the compiler.

**Comment by bkircher** [comment]
Thanks for filing the issue!

> Just the usual encoding problem.

I see two different issues here:

1. **ews-cpp must** escape characters that need to be escaped with regards to XML as the transport format
2. ews-cpp is programmed in a [way](http://utf8everywhere.org/) (particularly rapidxml underneath) that it expects all std::string and const char* contents to be valid UTF-8 code points hence **the user needs to make sure** all strings passed to ews-cpp are encoded in UTF-8

Does this makes sense? Does this work for you?

**Comment by SebastianBecker2** [comment]
It makes a lot of sense and it works like a charm.
