### ISSUE TITLE
body_type in get_item_impl

### ISSUE THREAD

**Issue by SebastianBecker2** [otris/ews-cpp#105]
The get_item_impl function doesn't specify the BodyType in the GetItem operation. Thus it's using the default value, which is body_type::best.
To specify the body_type, another parameter would be required.
To avoid having too many parameters for the get_item_impl (and the corresponding get_task, get_contact, get_calendar_item and get_message), I propose putting base_shape, std::vector<property_path>, std::vector<extended_field_uri> and body_type into a new item_shape class. It matches the structure in the ews operation itself.
https://msdn.microsoft.com/en-us/library/office/aa565261(v=exchg.150).aspx
This would reduce the number of overloads and allows the item_shape to be easily extended. And it reduces duplicate code since item_shape creates the respective xml itself.

I plan on requesting a pull (making a pull request?) end of next week.
Any suggestions or critique is welcome.

**Comment by bkircher** [comment]
Great! Sounds all reasonable. I'd definitely consider merging such a PR. `<ItemShape>` is not only used in `<GetItem>`, but also in `<FindItem>` and `<SyncFolderItems>`.

**Comment by SebastianBecker2** [comment]
Apparently  I forgot to close the issue after the PR was merged.
