### ISSUE TITLE
WorkingElsewhere in LegacyFreeBusyStatus

### ISSUE THREAD

**Issue by SebastianBecker2** [otris/ews-cpp#116]
Apparently Exchange Online and Exchange 2013 now has a WorkingElsewhere status.
It seems to be a kind-of replacement for OutOfOffice which is not supported anymore with current Outlook and OWA. Though it seems to still be supported as well.

As of right now, calendar_item::get_legacy_free_busy_status() complains when it gets the WorkingElsewhere status.

I'm actually not 100% sure how ews-cpp plans on handling such differences between version. Ofc there is the selection of the server version when creating the service.
Should it throw when the status is incompatible with the Exchange version?
This would increase the complexity of get_legacy_free_busy_status() and set_legacy_free_busy_status().

**Comment by bkircher** [comment]
The idea is (or at least was) that depending on the value of `basic_service::server_version_` (see docs [here](https://otris.github.io/ews-cpp/classews_1_1basic__service.html#ae196547e67268c5de7d044c79d33a7ed)) different XML could be generated before a request is made at run-time. However, we're currently using only Exchange 2013 SP2 schema and I don't recall we ever actually needed that. 

As for the `ews::free_busy_status` enum, I'd just add the new text value to it. The server will throw a schema validation error anyways.

**Comment by SebastianBecker2** [comment]
Sounds good to me. Will do so later today probably.
