### ISSUE TITLE
Schema validation error due to child element order in Exchange 2010

### ISSUE THREAD

**Issue by SebastianBecker2** [otris/ews-cpp#129]
I ran into a ton of problems trying to use the lib with an actual Exchange Server 2010.

The server complains about schema validation errors. For example in ItemShape the FilterHtmlContent would be invalid. Though the doc says it's supported: [Exchange 2010 ItemShape doc](https://docs.microsoft.com/en-us/previous-versions/office/developer/exchange-server-2010/aa565261(v%3dexchg.140)) Turns out, Exchange 2010 is really picky about the ordering of the child elements. Fixing `item_shape::to_xml()` to put the child elements into the stringstream in the order as shown in the docs, fixes the problem.

Using Exchange 2013 with server_version::exchange_2010 does **NOT** cause the same issue. It only happens when actually using Exchange 2010.

I'm going to work my way through... everything and try to fix this. But it's important to keep in mind for future implementation of operations. Always comply with the order in the docs...

**Comment by bkircher** [comment]
Would help if we had 2010 in testing infrastructure. If we had only test infra 😐

**Comment by SebastianBecker2** [comment]
BTW: Exchange 2010 SP2 is complaining about the "RequestServerVersion" when I specify `server_version::exchange_2010` when I call the GetItem operation.
Using the `server_version::exchange_2010_sp2` or `server_version::exchange_2010_sp1` does work.

Though using `server_version::exchange_2010` on an Exchange 2013 works flawlessly.

So not only is Exchange 2010 picky about the order. But also about the selected service pack version used in the request.

I planned on always using `server_version::exchange_2010` since that's the first version supporting all operations I need. Thus not requiring the user to select the version in the first place. But that doesn't seem to be possible anymore...

**Comment by SebastianBecker2** [comment]
The order of child elements for the Message element is specified by the order the set-functions of the `message` class object are called. The set-functions store the xml elements directly into the xml_subtree.

**Comment by SebastianBecker2** [comment]
Update: We just dropped Exchange 2010 support for our project.
We might get back to it in the future. But it's highly unlikely.

Meaning, I won't be able to work on this issue.
Though I will try to respect child element ordering for new operations I will add in the future.

I would vote to close the issue and leave the code as is for now.

**Comment by bkircher** [comment]
Go ahead. Sounds sensible.
