### ISSUE TITLE
drafts with empty "To"

### ISSUE THREAD

**Issue by Izulle** [otris/ews-cpp#134]
ews-cpp throws exception if "To" is empty. 
see around line 9485 in ews.hpp

>         if (!id.valid())
        {
            check(!address.empty(),
                  "<EmailAddress> element value can't be empty");

            return mailbox(std::move(address), std::move(name),
                           std::move(routing_type), std::move(mailbox_type));
        }

But I can create draft without recipient and it is ok.  "Other" clients afford it and show correctly.
Moreover, I can move such draft into  inbox and thus have  message with no recipients in inbox.

I will ignore this exception in my code. Just wanted to let you know.

**Comment by Izulle** [comment]
My colleage recommended 

> iMac-iMac3:ews dzakamskaya$ git diff
diff --git a/include/ews/ews.hpp b/include/ews/ews.hpp
index 2608cf7..ccfb531 100644
--- a/include/ews/ews.hpp
+++ b/include/ews/ews.hpp
@@ -394,13 +394,22 @@ public:
 };
 
 //! Raised when an assertion fails
-class assertion_error final : public exception
+class assertion_error final: public exception
 {
 public:
     explicit assertion_error(const std::string& what) : exception(what) {}
     explicit assertion_error(const char* what) : exception(what) {}
 };
 
+class no_recipient_error final : public exception
+{
+public:
+    explicit no_recipient_error(const std::string& what) : exception (what) {}
+    explicit no_recipient_error(const char* what) : exception (what) {}
+};
+
+    
+    
 //! Raised when a response from a server could not be parsed
 class xml_parse_error final : public exception
 {
@@ -9481,7 +9490,7 @@ public:
 
         if (!id.valid())
         {
-            check(!address.empty(),
+            check<no_recipient_error>(!address.empty(),
                   "<EmailAddress> element value can't be empty");
 
             return mailbox(std::move(address), std::move(name),

**Comment by SebastianBecker2** [comment]
I think there is a misunderstanding here. Maybe on my part though...

In your initial post, you reference `static mailbox from_xml_element(const rapidxml::xml_node<>& elem)` which converts an xml node to a mailbox object.
Those have to have an ItemId OR a EmailAddress.

An ews::message object returns a vector of mailboxes for the recipients. Which in my case is empty when I try to get the recipients of a draft that doesn't contain any yet.

What I tried is:
I created a draft with a subject and body. Without a recipient or cc recipient.
I moved the draft into the inbox.
I iterated over all item_ids in the inbox with the following code:

    for (const auto& item_id : item_ids)
    {
        auto message = service.get_message(item_id);

        std::cout << "Subject: " << message .get_subject() << "\n";
        for (const auto& recipient : message .get_to_recipients())
        {
            std::cout << "Recipient: " << recipient.value() << "\n";
        }
    }

This works for me without throwing any exceptions.
The response to the GetMessage operation should not contain either the ToRecipient or CcRecipients (or BccRecipients) nodes. Thus the `static mailbox from_xml_element(const rapidxml::xml_node<>& elem)` shouldn't be called in the first place.

**Comment by Izulle** [comment]
May be it depends on how do one made draft.
I am open Mail  (standart) on iPad. Create message without sender and save it as draft.
Then a am trying to download it using ews-cpp (and some ObjectiveC around). There are definitely valid itemId cause message object was recieved by 
`auto msgs = self.service->get_messages(item_ids, allPropertiesShape);`
but i got this exception

see screenshot

https://ibb.co/F4sM5Kz

**Comment by SebastianBecker2** [comment]
I'm not 100% sure but it might be possible the mail client on the iPad defined Mailbox element without content. Or at least without ID nor mail address.
But I can't really figure out if that is legal or not.
The documentation of the [mailbox element](https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/mailbox) states that all child elements are optional without further specification that at least ID or mail address has to be specified.
Though it says that one of the child elements is [EmailAddress (NonEmptyStringType)](https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/emailaddress-nonemptystringtype) which states:
"The EmailAddress element is the only required Mailbox element."

Nevertheless I'm not sold on the no_recipient_error. Mainly because it could also occur for other mailboxes that do not define the recipients.

Maybe `from_xml_element(const rapidxml::xml_node<>&)` returns a default constructed mailbox if it doesn't contain an ID or mail address? That is what `get_sender()` returns when there is no sender.
That would make sense to me.
(I wonder if it would break my code...)

**Comment by bkircher** [comment]
> Nevertheless I'm not sold on the no_recipient_error. Mainly because it could also occur for other mailboxes that do not define the recipients.
I second that. Also: using exceptions for normal control flow in C++ is not recommended.

One thing that I noticed is that the check in `mailbox::from_xml_element` is only executed with XML that comes from an MS Exchange server. So if an Exchange server sends this kind of payload, maybe the check is just wrong here?

@lzulle can you give us an example request/response (the XML would be enough) where this happens?
Also, you can just remove the check from your code and see how far this gets you.

**Comment by SebastianBecker2** [comment]
I finally got it reproduced. Though not 100% clear how I did it. And I don't really have the time to investigate.
Though I can say, the mailbox does only have to elements. The name and the type. Type being 'OneOff' in this case. OWA displays the mailbox properly in the mail.
All seems pretty legit. So I will just remove the check for the address element.
