### ISSUE TITLE
create_item returns not valid id.

### ISSUE THREAD

**Issue by premchedella** [otris/ews-cpp#136]
I wrote a small function where I want to send an attachment.
The code is written in Qt and C++.
I am getting `item_id`  is not valid.  If I use `service.create_item(message, ews::message_disposition::save_only);` then `item_id` is valid but `service.send_item(item_id);` is failing because of `Change_Key ` is not valid and changed.

For sensitive reasons, I the server information is empty.  Otherwise I am able to send message without attachment.

I looked into the test code and followed the same.  Kindly help me in this case.  

Thank you.

```
void EwsTest()
{  
  int res = EXIT_SUCCESS;
  ews::set_up();

  try
  {    
    QString server_uri = "";
    QString domain = "";
    QString user_name = "";
    QString password = "";
    ews::service service = ews::service(server_uri.toStdString(), domain.toStdString(), user_name.toStdString(), password.toStdString());

    QString subject = "Test mail";   
    std::vector<ews::mailbox> recipients;
    recipients.push_back(ews::mailbox("xxxxx"));

    ews::message message = ews::message();
    message.set_to_recipients(recipients);
    message.set_subject(subject.toStdString());
    
    QString body_text = "<b>This is a test.</b> <br> This another one.";
    auto body = ews::body();
    body.set_content(body_text.toStdString());
    body.set_type(ews::body_type::html);

    message.set_body(body);

    ews::item_id item_id = service.create_item(message,
        ews::message_disposition::send_and_save_copy);

    if (!item_id.valid())
    {
      std::cout << "Item Id not valid." << std::endl;
    }
       
    QString attachment_file ="";
    message = service.get_message(item_id);     
    auto attachment = ews::attachment::from_file(attachment_file.toStdString(), "application/doc", "test.docx");
    auto attachment_id = service.create_attachment(message.get_item_id(), attachment);
    
    if (!attachment_id.valid())
    {
      std::cout << "Attachment ID is not valid." << std::endl;
    }
    if (attachment_id.root_item_id().id().empty())
    {
      std::cout << "Attachment Root ID is empty." << std::endl;
    }     
    //service.send_item(item_id);
  }  catch (std::exception& exc)
  {
    std::cout << exc.what() << std::endl;
    res = EXIT_FAILURE;
  }
  ews::tear_down();
}
```

**Comment by SebastianBecker2** [comment]
I just did the same myself a few days ago.
create_attachment(...) returns not just the attachment_id.
It returns an object that contains the attachment_id of the newly created attachment as well as the item_id of the message with a new change_key for that message.

**Comment by SebastianBecker2** [comment]
Try something like this:
    message = service.get_message(item_id);
    auto message_id = message.get_item_id();
    auto attachment = ews::attachment::from_file(attachment_file.toStdString(), "application/doc", "test.docx");
    auto attachment_id = service.create_attachment(message.get_item_id(), attachment);
    message_id = attachment_id.root_item_id();
    service.send_item(item_id);

**Comment by premchedella** [comment]
>@SebastianBecker2
 ```
auto attachment = ews::attachment::from_file(attachment_file.toStdString(), "application/doc", "test.docx");
    auto attachment_id = service.create_attachment(item_id, attachment);
    item_id = attachment_id.root_item_id();
    service.send_item(item_id);
```
As you suggested with the above, I am able to send an attachment.  Thanks for the suggestion.  I also want to save this email to my  **Sent Items**.  How can I do this, please.

**Comment by bkircher** [comment]
>  I also want to save this email to my Sent Items. How can I do this, please.

Take a look at `ews::message_disposition::send_and_save_copy`.
