### ISSUE TITLE
[Question]: Message with body and attachment

### ISSUE THREAD

**Issue by premchedella** [otris/ews-cpp#137]
I would like write a function which uses ews class to send an email with body and attachment and once the message is sent that message has to be in **Sent Items** folder.

Following is the code.  For the security purpose, I kept server credentials and recipients email id as empty (in this post).

```
void EwsTest1()
{
  std::cout << " Microsoft Exchange Web Services Test." << std::endl;

  int res = EXIT_SUCCESS;
  ews::set_up();

  try
  {
    QString server_uri = "";
    QString domain = "";
    QString user_name = "";
    QString password = "";

    ews::service service = ews::service(server_uri.toStdString(), domain.toStdString(),
      user_name.toStdString(), password.toStdString());

    QString subject = "Test mail from outer space";
    std::vector<ews::mailbox> recipients;
    recipients.push_back(ews::mailbox(""));

    ews::message message = ews::message();
    message.set_to_recipients(recipients);
    message.set_subject(subject.toStdString());

    QString body_text = "<b>This is a test.</b> <br> This another one.";
    auto body = ews::body();
    body.set_content(body_text.toStdString());
    body.set_type(ews::body_type::html);

    message.set_body(body);

    const ews::distinguished_folder_id 
        sent_item = ews::standard_folder::sent_items;

    ews::item_id item_id = service.create_item(message,
          ews::message_disposition::save_only);
        //ews::message_disposition::send_and_save_copy);
      
          
    if (!item_id.valid())
    {
      std::cout << "Item Id not valid." << std::endl;
    }

    QString attachment_file =
      "E:/projects/tools/email_automation/data/test.docx";    

    message = service.get_message(item_id);

    auto attachment = ews::attachment::from_file(attachment_file.toStdString(),
        "application/doc", "test.docx");

    auto attachment_id = service.create_attachment(message.get_item_id(),
      attachment);

    if (!attachment_id.valid())
    {
      std::cout << "Attachment ID is not valid." << std::endl;
    }

    if (attachment_id.root_item_id().id().empty())
    {
      std::cout << "Attachment Root ID is empty." << std::endl;
    } 
        
    item_id = attachment_id.root_item_id();    
    service.send_item(item_id);       
  }
  catch (std::exception& exc)
  {
    std::cout << exc.what() << std::endl;
    res = EXIT_FAILURE;
  } 
}
```

If I use create message item with the  `ews::item_id item_id service.create_item(message,         ews::message_disposition::save_only);` then I can send an email with body and attachment but that message is **not saving in Sent Items** folder.  

if I use create message item with the `
 ews::item_id item_id = service.create_item(message,         
ews::message_disposition::send_and_save_copy); ` then only body of the message sent and copy of the message presents in the **Sent Items** folder and not attachment since _send and save_ message disposition.    Also the` item_id` is not valid and going to `catch` block.  

Kindly help me to send a message with body and attachment that has to save the message Sent Items folder once message is sent.

**Comment by mailwl** [comment]
you have to create message to Draft folder

**Comment by premchedella** [comment]
I just made the following changes:
```
const ews::distinguished_folder_id drafts = ews::standard_folder::drafts;
ews::item_id item_id = service.create_item(message,        
        ews::message_disposition::save_only, drafts);
```

Once the message is sent, I didn't see the message in my **Sent Items** folder.

**Comment by SebastianBecker2** [comment]
I think the fact that 

> the` item_id` is not valid and going to `catch` block.

is probably the thing to look after first. I'm almost certain it causes your problem in the first place.

You create a new message with `ews::item_id item_id = service.create_item(message, ews::message_disposition::save_only);`
Try specifying the drafts folder with

    auto draft_folder = ews::distinguished_folder_id(
			ews::standard_folder::drafts);
    auto item_id = service.create_item(message,
          ews::message_disposition::save_only, draft_folder);

After doing so, you shouldn't need to `message = service.get_message(item_id);` before attaching the attachments. All you need is the item_id of the message anyway. And you already got that when creating the message in the drafts folder.

    auto attachment = ews::attachment::from_file(attachment_file.toStdString(),
        "application/doc", "test.docx");

    auto attachment_id = service.create_attachment(message.get_item_id(),
      attachment);

Creation and attaching the attachment good too. If you stop after the call to `create_attachment`, you should be able to see the message in the drafts folder with the attachments attached. Just check in your Outlook/OWA after stepping through the calls.

The checks on the `attachment_id` and the `root_item_id` in the `attachment_id` shouldn't be necessary. When `create_attachment` is called with the proper parameters and it doesn't throw any exception, you should be good to go.

**Comment by SebastianBecker2** [comment]
Overall it should look something like this:
    const ews::distinguished_folder_id 
        draft_folder = ews::standard_folder::drafts;

    ews::item_id item_id = service.create_item(message,
          ews::message_disposition::save_only, draft_folder);

    QString attachment_file =
      "E:/projects/tools/email_automation/data/test.docx";

    auto attachment = ews::attachment::from_file(attachment_file.toStdString(),
        "application/doc", "test.docx");

    auto attachment_id = service.create_attachment(item_id,
      attachment);

    item_id = attachment_id.root_item_id();
    service.send_item(item_id);

**Comment by SebastianBecker2** [comment]
And in case you want to attach multiple attachment, keep in mind that you have to use the root_item_id from each previous `create_attachment` call.

Something like:

    const ews::distinguished_folder_id 
      draft_folder = ews::standard_folder::drafts;
    ews::item_id item_id = service.create_item(message,
      ews::message_disposition::save_only, draft_folder);

    for (const QString& attachment_file : list_of_attachment_files)
    {
      auto attachment = ews::attachment::from_file(attachment_file.toStdString(),
        get_mime_type_from_file(attachment_file), get_filename_from_file(attachment_file);

      auto attachment_id = service.create_attachment(item_id, attachment);

      item_id = attachment_id.root_item_id();
    }
    
    const ews::distinguished_folder_id sent_folder = ews::standard_folder::sent_items;
    service.send_item(item_id, sent_folder);

**Comment by premchedella** [comment]
> 
> 
> Overall it should look something like this:
> 
> ```
> const ews::distinguished_folder_id 
>     draft_folder = ews::standard_folder::drafts;
> 
> ews::item_id item_id = service.create_item(message,
>       ews::message_disposition::save_only, draft_folder);
> 
> QString attachment_file =
>   "E:/projects/tools/email_automation/data/test.docx";
> 
> auto attachment = ews::attachment::from_file(attachment_file.toStdString(),
>     "application/doc", "test.docx");
> 
> auto attachment_id = service.create_attachment(item_id,
>   attachment);
> 
> item_id = attachment_id.root_item_id();
> 
> const ews::distinguished_folder_id 
>     sent_folder = ews::standard_folder::sent_items;
> service.send_item(item_id, sent_folder);
> ```

The worked and now I am able to see the both message and attachment and it saved in the **Sent Items** folder.

**Comment by premchedella** [comment]
Thank you so much for the suggestions and code, @SebastianBecker2 and @mailwl .
Also, closing this question as I got the solution.

**Comment by premchedella** [comment]
Closed this question as I got the solution.
