### ISSUE TITLE
Authentication as application with ews-cpp

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [otris/ews-cpp#146]
Hello. Thank you a lot for such useful library!
I have one question - is it possible with this library to authenticate on Exchange Online as application, which is registered on Azure AD?
Thank you.

**Comment by bkircher** [comment]
Hi. Yeah, _should_ be no problem as long as EWS is enabled.

**Comment by ZaMaZaN4iK** [comment]
I am a little bit disappointed how to do it - because of all examples trying to connect as user (even `ews::service` ctor wants user and password).

**Comment by m-Schlitzer** [comment]
If I understand correctly this means you want to use OAuth2 with EWS. Thats a problem. After seeing #148 and digging around a little it seems you need Azure AD Authentication Library. I have not found a C++ implementation of said library as of yet.
So far the only authentication methods are basic authentication and ntlm.

**Comment by kmorrissey-mersive** [comment]
Is it really necessary to use specifically Azure AD Authentication, or might a more generic OAuth2 library work?

**Comment by kmorrissey-mersive** [comment]
Is anyone in a position to judge whether https://github.com/Microsoft/cpprestsdk has code applicable to what is needed?

**Comment by ZaMaZaN4iK** [comment]
Hmm... I am note sure that we really need any specific Azure AD library because at work we are working with MS Graph API ans EWS API without any special libraries for this - just HTTP requests to some endpoints and work with JWT.

Even CURL will be enough here (but I prefer more convinient and high-level libraries for making HTTP requests)

**Comment by idolum** [comment]
I think, I can close this issue, as it is addresse in #148. An implementation using the client credentials flow is available (see #163). The provided example works with a given AD tenant. But the registered client needs the application permission "FullAccess". The ROPC flow will be supported as well, but will be resolved as part of #148.
