### ISSUE TITLE
ResolveNames operation parsing error

### ISSUE THREAD

**Issue by SebastianBecker2** [otris/ews-cpp#151]
I'm trying to get the primary smtp address of a user.
One, or probably the best way, I found was to use the ResolveNames operation.
But trying to do so, using search_scope::active_directory crashes on parsing the response.
I do get a mailbox but I also get contact information about the user. And those contact information do not include a DirectoryId, which is expected by the parse function.

Following the request:
```xml
<m:ResolveNames ReturnFullContactData="true" SearchScope="ActiveDirectory" >
	<m:UnresolvedEntry>sebastian.becker</m:UnresolvedEntry>
</m:ResolveNames>
```

And the response:
```xml
<m:ResolveNamesResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
	<m:ResponseMessages>
		<m:ResolveNamesResponseMessage ResponseClass="Success">
			<m:ResponseCode>NoError</m:ResponseCode>
			<m:ResolutionSet TotalItemsInView="1" IncludesLastItemInRange="true">
				<t:Resolution>
					<t:Mailbox>
						<t:Name>Sebastian Becker</t:Name>
						<t:EmailAddress>sebastian.becker@regisafe.rocks</t:EmailAddress>
						<t:RoutingType>SMTP</t:RoutingType>
						<t:MailboxType>Mailbox</t:MailboxType>
					</t:Mailbox>
					<t:Contact>
						<t:Culture>de-DE</t:Culture>
						<t:DisplayName>Sebastian Becker</t:DisplayName>
						<t:GivenName>Sebastian</t:GivenName>
						<t:Initials/>
						<t:CompanyName/>
						<t:EmailAddresses>
							<t:Entry Key="EmailAddress1">SMTP:sebastian.becker@regisafe.rocks</t:Entry>
						</t:EmailAddresses>
						<t:PhysicalAddresses>
							<t:Entry Key="Business">
								<t:Street/>
								<t:City/>
								<t:State/>
								<t:CountryOrRegion/>
								<t:PostalCode/>
							</t:Entry>
						</t:PhysicalAddresses>
						<t:PhoneNumbers>
							<t:Entry Key="AssistantPhone"/>
							<t:Entry Key="BusinessFax"/>
							<t:Entry Key="BusinessPhone"/>
							<t:Entry Key="HomePhone"/>
							<t:Entry Key="MobilePhone"/>
							<t:Entry Key="Pager"/>
						</t:PhoneNumbers>
						<t:AssistantName/>
						<t:ContactSource>ActiveDirectory</t:ContactSource>
						<t:Department/>
						<t:JobTitle/>
						<t:OfficeLocation/>
						<t:Surname>Becker</t:Surname>
					</t:Contact>
				</t:Resolution>
			</m:ResolutionSet>
		</m:ResolveNamesResponseMessage>
	</m:ResponseMessages>
</m:ResolveNamesResponse>
```

As you can see, the contact element does contain information. but those are not an actual contact from a contact list. But contact information from a ContactSource.

My idea was to replace the DirectoryId in the resolve_names_response_message with the actual contact. Using ews::contact::from_xml(...) to parse the contact from the response.
Problem is, from_xml(...) expects an item_id. Which is not available as well. And which, I assume, is the same as the DirectoryId. Though not 100% on that.

Anyone have any ideas on how to solve this properly? Why was the DirectoryId assumed to be available? I guess it's always there when the name is found in a contact list!?
Changing ews::contact to not require an item_id? That might proof to be more extensive than it sounds.

**Comment by idolum** [comment]
I think it is a bug. According to the XSD `DirectoryId` is an optional element. So, the `resolve_names_response_message::parse()` should handle the case of a missing `DirectoryId`.

And I also think that `DirectoryId` and `ItemId` are something different. It depends where the contact information comes from. If comes from Exchange then it is an item within Exchange and has an `ItemId`.  If it comes from a third-party ressource like the AD, then it does not have an `ItemId`, but might have an `DirectoryId`.

At least, this how I understood the ressources that I found on this topic, e.g. on the  the `FindPeople` [1] operation and the summary of how contact information is provided in Exchange [2].

[1] https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/findpeople-operation
[2] https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/people-and-contacts-in-ews-in-exchange
