### ISSUE TITLE
FilterHtmlContent invalid element on Exchange 2013

### ISSUE THREAD

**Issue by SebastianBecker2** [otris/ews-cpp#153]
We're having issues with the GetItem Message with one of our customers Exchange 2013 (SP1?).

Exchange complains that:
The element 'ItemShape' in namespace 'http://schemas.microsoft.com/exchange/services/2006/messages' has invalid child element 'FilterHtmlContent' in namespace 'http://schemas.microsoft.com/exchange/services/2006/types'."

ItemShape is set up with an extended_field_uri vector, base_shape::all_properties and body_type::html.

The constructor for item_shape sets filter_html_content to false. And this value isn't changed. So the request contains <t:FilterHtmlContent>false</t:FilterHtmlContent>.

The schema version in the request is Exchange2010 since that is the oldest we want to support.
According to the documentation I found, FilterHtmlContent isn't available on 2007. And that it is available with 2010. So I can only assume, it should be available in 2013 as well.
I have no issues with our own Exchange 2016 test server, nor with our Office365 Exchange Cloud Server.

Does anyone have any idea on this?

**Comment by idolum** [comment]
I do not have a specific idea, but I checked it with our Exchange instance (Exchange2013_SP1). If I retrieve the XSD for the types from our Exchange instance, I get for the types namespace (http://schemas.microsoft.com/exchange/services/2006/types) a XSD wih the `ItemResponseShapeType` having the `FilterHtmlContent` as an optional boolean element.

Have you tried to retrieve the XSD from your customer's instance? If it is an 2013 SP1 you should at least get the same results as I did.

**Comment by SebastianBecker2** [comment]
Thanks a lot for the tip. I will try to get XSDs from that customers Exchange Server and check.

**Comment by SebastianBecker2** [comment]
We figured it out. Though in my opinion, it's a bug in Exchange 2013. But I don't dare to wrap my head around this nightmare anymore.

Since we tried to provide support for all Exchange Versions from 2010 upwards, we used the schema version Exchange2010.
Event though as we figured out in #129 that Exchange2010 and earlier is not possible with ews-cpp.
But we kept the schema version Exchange2010 as the lowest common denominator.

Exchange 2013 seems to have a ton of problems with schema version Exchange2010. Problems we didn't face on Exchange 2016, 2019 and 365.

Changing the schema version to Exchange2013 solved the problem.
Still have to test with Exchange 2013 and all newer version. Not sure what demons lay ahead.

I hope this is helpful to others.
Think about implementing Autodiscovery, which returns the schema version for the server (afaik).
Or providing an setting for the user to specify the version.

**Comment by idolum** [comment]
Thank you Sebastian for the feedback! I read the the Autodiscover process can be used to [to determine the XSD version](https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/ews-schema-versions-in-exchange), but I haven't got a clue yet, how this can be done. A good candidate seems to be the [RequestServerVersion](https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/requestserverversion) element in the SOAP message.

**Comment by SebastianBecker2** [comment]
One correction on my previous comment:
Changing the schema version to Exchange2013 was not enough. It just triggered different schema validation errors on different operations.
Changing to schema version Exchange2013_SP1 however solved the problem for now...

What I did found out with certainty is that the XSD specifies that elements have to be in a specific order. Or rather in a specific sequence. Using the xs:sequence element.

This seems to be the case for current XSDs as well. Meaning even on Exchange 2016, Exchange 2019 and Office 365 a proper schema validation should reject messages from ews-cpp. But they don't for some reason. And I hope they never will.

**Comment by idolum** [comment]
Thanks, Sebastian! At least, we have to keep this in mind for the future.
