### ISSUE TITLE
SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by premchedella** [otris/ews-cpp#160]
I am getting the following error:
SSL peer certificate or SSH remote key was not OK

It used to work properly in the older work station and with the new work station, I am getting the above error.  How to resolve the error, please?

**Comment by premchedella** [comment]
```
void EmailEws::SendSimple()
{
  ews::set_up();

  try
  {
    ews::service service = ews::service(server_uri_, domain_, user_name_,
        password_);    
    
    ews::message message = ews::message();
    message.set_to_recipients(to_recipients_);

    if (cc_recipients_.size() > 0)
    {
      message.set_cc_recipients(cc_recipients_);
    }

    if (bcc_recipients_.size() > 0)
    {
      message.set_cc_recipients(bcc_recipients_);
    }

    message.set_subject(subject_);
        
    auto body = ews::body();
    body.set_content(message_block_.toStdString());
    body.set_type(body_type_);
    message.set_body(body);

    service.create_item(message, ews::message_disposition::send_and_save_copy);
  }
  catch (std::exception& exc)
  {
    std::cout << exc.what() << std::endl;
  }
}

```

`service.create_item` throwing an error with the **SSL peer certificate or SSH remote key was not OK**

**Comment by idolum** [comment]
I guess the curl library throws this error, as the SSL certificate of your server seems to be invalid. Two questions to check this:

* What do you get, if open your server uri with curl?
* What do you get, if you disable the certificate certification? You can disable it by the CMake option `DISABLE_TLS_CERT_VERIFICATION`.

**Comment by premchedella** [comment]
As suggested in the above, developed a function, it works property, no error thrown.
```
bool EmailEws::IsConnected()
{
  bool is_valid = false;
  ews::set_up();

  try
  {    
    ews::service service = ews::service(server_uri_, domain_, user_name_,
        password_);
    is_valid = true;
  }
  catch (std::exception& exc)
  {
    std::cout << exc.what() << std::endl;
  }

  return is_valid;
}
```
`DISABLE_TLS_CERT_VERIFICATION` is already disabled (low light and font changes) in `ews.hpp` file.
```
#ifdef EWS_DISABLE_TLS_CERT_VERIFICATION
            // Warn in release builds
#    ifdef NDEBUG
#        pragma message(                                                       \
            "warning: TLS verification of the server's authenticity is disabled")
#    endif
            // Turn-off verification of the server's authenticity
            set_option(CURLOPT_SSL_VERIFYPEER, 0L);
            set_option(CURLOPT_SSL_VERIFYHOST, 0L);

#endif
```

Should I get a new SSL certificate for client?  Or any directions, please.

**Comment by premchedella** [comment]
```
#define EWS_DISABLE_TLS_CERT_VERIFICATION 0

#include <ews\ews.hpp>
#include <ews\ews_fwd.hpp>
```

I added `#define EWS_DISABLE_TLS_CERT_VERIFICATION 0` before the header files, I see the emails are being sent.  

But I don't want to disable TLS Certification verification.  Let me know what the ways, please?

**Comment by idolum** [comment]
Then it seems to me that there is an issue with your certificate. Maybe it is outdated or self-signed. 

You can check this by open the EWS server URL in a browser. After you added your credentials the browser should provide you with some information on the certificate. Usually, by clicking on the icon next to the URL in the address line.

Another option would be to open with curl. Something like `curl -vvI <URL>`

**Comment by premchedella** [comment]
Thanks for the comments.

I was able to open EWS server in the browser, at the prompt, given user credentials.    Where can I find the certificates in the Windows PC and can copy that certificate in my executable path, this is may be a stupid question.

**Comment by idolum** [comment]
Click on the lock icon next the URL in your browser. In Firefox it looks like this

![grafik](https://user-images.githubusercontent.com/1178743/69350546-0c4ae600-0c7a-11ea-9a4f-f732cc0d57db.png)

Then you should get details on the certificate used.

**Comment by premchedella** [comment]
After clicking on the **lock** icon.  Now it's working.  Thank you so much for the support.

**Comment by idolum** [comment]
You are welcome!
