### ISSUE TITLE
Does the auth authentication support the negotiate method?

### ISSUE THREAD

**Issue by BAMSHK** [otris/ews-cpp#214]

**Comment by idolum** [comment]
@BAMSHK Hi, what do you mean by negotiate method? [Microsoft Negotiate](https://learn.microsoft.com/de-de/archive/blogs/dsnotes/negotiate-vs-ntlm)? So far, this is not implemented. Just Basic, NTLM and OAuth2 (Client Credentials and Ressource Owner Password).

**Comment by BAMSHK** [comment]
thank&nbsp;you


503533380
***@***.***



        



         Original
         
       
From:                  "Veit Jahns"         ***@***.***&gt;                 
Sent Time:         2024-11-27- 15:38 
To:                  "otris/ews-cpp"         ***@***.***&gt;                 
Cc:                  "BAMSHK"         ***@***.***&gt;         ,                "Mention"         ***@***.***&gt;                 
Subject:         Re: [otris/ews-cpp] Does the auth authentication support thenegotiate method? (Issue #214) 




@BAMSHK&nbsp;Hi, what do you mean by negotiate method? Microsoft Negotiate? So far, this is not implemented. Just Basic, NTLM and OAuth2 (Client Credentials and Ressource Owner Password).
