### ISSUE TITLE
Add public CI

### ISSUE THREAD

**Issue by bkircher** [otris/ews-cpp#25]
- Additionally to internal Jenkins jobs, add AppVeyor and Travis CI jobs to help with PRs
- Split-up all tests in OfflineXYZ and normal tests, OfflineXYZ tests should not require a running Exchange server
- Add some nice "Build Passing" badges to README

**Comment by raldus** [comment]
Its a Pleasure for me.

**Comment by bkircher** [comment]
Thank you for working on this!
