### ISSUE TITLE
basic auth for ews::service

### ISSUE THREAD

**Issue by KoffeinKaio** [otris/ews-cpp#56]
At the moment, I'm playing with online ews (https://outlook.office365.com/EWS/Exchange.asmx).

It seems like ews::service automatically uses ntlm - office365 requires basic auth. 
Also there is no ews::server_version::exchange2016.

I created a workaround giving ews:service constructor an useBasic bool, is this just not implemented or am I missing some way to do this there?

**Comment by bkircher** [comment]
Hi! It is simply not implemented yet. Office 365 is on the list but not very high priority.

Both, basic_authentication and the new Exchange server version shouldn't be very hard to add, though.

**Comment by bkircher** [comment]
Okay, I can connect now to outlook.office365.com with basic auth and retrieve calendar items. I'll change the basic_service API to allow for authentication methods other than NTLM and add an example on how to connect to Office 365 via EWS. Thanks for reporting!

**Comment by KoffeinKaio** [comment]
Great, Thanks. 
I'm working on synching a Contact DB with the GAL in EWS, I'll report back when it's done.

**Comment by bkircher** [comment]
> Also there is no ews::server_version::exchange2016.

About this one: I didn't find a new [`<RequestServerVersion>`](https://msdn.microsoft.com/en-us/library/office/bb891876(v=exchg.150).aspx) value for Exchange 2016. This makes sense to me because AFAIK the EWS schema didn't change with 2016 release.
