### ISSUE TITLE
 Implement item property <ExtendedProperty>

### ISSUE THREAD

**Issue by bkircher** [otris/ews-cpp#7]
Note: there is already code in an internal merge request by @raldus.

**Comment by bkircher** [comment]
Mostly done but we have to think about on how to integrate that into basic_service's get_{message,contact,...} and update_item overload sets. So still some work to do here.

**Comment by raldus** [comment]
I look for it

**Comment by bkircher** [comment]
Yeah, we need to finish other things first, so no hurry.

**Comment by bkircher** [comment]
New issue for the remaining changes here: #54. This here is done
