### ISSUE TITLE
Not coonect to server

### ISSUE THREAD

**Issue by Khushvakt** [otris/ews-cpp#78]
Hello, I do not connect to the server.
Here's the code:
`#include <ews/ews.hpp>
#include <ews/ews_test_support.hpp>
#include <cstdlib>
#include <exception>
#include <iostream>
#include <ostream>
#include <string>
#include <vector>

int main()
{
    int res = EXIT_SUCCESS;
    ews::set_up();

    try
    {
        //const auto env = ews::test::environment();
        auto service = ews::service("############", "########", "##########",
                                    "##############");

        auto message = ews::message();
        message.set_subject("Test mail from outer space");
        std::vector<ews::mailbox> recipients;
        recipients.push_back(ews::mailbox("#####.####@#####.##"));
        message.set_to_recipients(recipients);
        auto text = ews::body("(Welcome!)\n\nThis is a test.\n");
        message.set_body(text);
        service.create_item(message,
                            ews::message_disposition::send_and_save_copy);
    }
    catch (std::exception& exc)
    {
        std::cout << exc.what() << std::endl;
        res = EXIT_FAILURE;
    }

    ews::tear_down();
    return res;
}
`
Here's the error:
![image](https://user-images.githubusercontent.com/33055962/33059012-39098468-ceb4-11e7-88b3-2879035b5560.png)

What am I doing wrong?

**Comment by bkircher** [comment]
Hi there.

The HTTP response status code 302 is a common way of performing URL redirection. An HTTP response with this status code will additionally provide a URL in the header field location. So, you are probably being redirected.

Can you run the `examples/autodiscover.cpp` example and paste the output here? (If you cannot or do not want to put the output here, can you make sure that "auto-discovered" URL is used as endpoint in the `ews::service` constructor in the code above?)
