### ISSUE TITLE
Replace Google Test with Catch2

### ISSUE THREAD

**Issue by bkircher** [otris/ews-cpp#90]

**Comment by bkircher** [comment]
Google Test is working okay most of the time and does the job. Lately it makes tests on AppVeyor and Travis CI shaky because of -Werror (warning treated as error). I believe it is stupid to make a build fail because of a warning triggered in the test framework library.

We could also do let the Google Test submodule point to a different repository or commit. Then we don't have to switch test frameworks.

**Comment by m-Schlitzer** [comment]
Doesn't work with VS2012, so we can use it once we upgrade our compilers.

**Comment by bkircher** [comment]
With your changes (4868350 and 619a748) the -Werror pain is gone. We wait with Catch decision after the compiler upgrade.
