### ISSUE TITLE
Character escaping is missing in ews::update.to_xml()

### ISSUE THREAD

**Issue by SebastianBecker2** [otris/ews-cpp#91]
ews::update.to_xml() is building the xml on it's own. And fails to escape the content properly.
The class item on the other hand uses xml_subtree which itself uses rapidxml to build the xml data. Thus taking care of proper escaping of characters.

To reproduce, just use update_item with a property value that contains an ampersand.

    ews::property property(ews::property_path("item:Subject", "Invalid subject &");
    ews::update update(property, ews::update::operation::set_item_field);
    service.udpate_item(item_id, update);

This causes an schema validation exception due to the unescaped ampersand.

**Comment by bkircher** [comment]
I can reproduce this
