### ISSUE TITLE
Implementation of folder operations

### ISSUE THREAD

**Issue by SebastianBecker2** [otris/ews-cpp#94]
Folder operations like FindFolder, CreateFolder, DeleteFolder, GetFolder, MoveFolder should be implemented.

I'm working on an implementation right now. FindFolder seems to work already.

**Comment by SebastianBecker2** [comment]
A few operations have been implemented in #96.
But others are still missing, like CreateManagedFolder, CopyFolder, MoveFolder, EmptyFolder, UpdateFolder.

I have to focus on other stuff right now. So I probably won't implement those myself. Maybe someone else feels the need to do it.

**Comment by bkircher** [comment]
> still missing, like CreateManagedFolder, CopyFolder, MoveFolder, EmptyFolder, UpdateFolder.

We open a new issue as soon someone needs these operations. Until then, thanks for your contributions!
