### ISSUE TITLE
Implementing SyncFolderItems operation

### ISSUE THREAD

**Issue by SebastianBecker2** [otris/ews-cpp#99]
I'm going to implement this operation now, since we desperately need it for our project.

Further information on how it works:
https://msdn.microsoft.com/en-us/library/office/aa563967(v=exchg.150).aspx

Basically a server managed sync that returns the complete list of items on first sync and all changes since the previous sync call on every consecutive sync call.

**Comment by bkircher** [comment]
Seems to be done with 3d9246b in PR #101. Thanks!
